version: '3.4'

networks:
  default:
    driver: bridge
services:
  api:
    build: .
    networks:
      - default
    volumes:
      - ./app/:/app
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "5000", "--reload"]
    ports:
    - "5000:5000"
    env_file:
      - .env