version: '3.4'

networks:
  default:
    driver: bridge
services:
  api:
    build: .
    networks:
      - default
    volumes:
      - ./app/:/app
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8080", "--reload"]
    ports:
    - "8080:8080"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
    - "5431:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
    postgres_data: