version: '3'

services:
  api:
    build:
      context: api
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    volumes:
      - ./api:/app

  front:
    build:
      context: front
      dockerfile: Dockerfile
