version: '3'

services:
  api:
    build:
      context: api
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    volumes:
      - ./api:/app

  front:
    build:
      context: front
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
        - ./front:/app
