version: "3.8"
services:
  api:
    build:
      context: ./api-example
    volumes:
      - ./api-example/:/app
    ports:
      - "5000:5000"
    env_file:
      - .env  
  frontend:
    build:
      context: ./frontend-example
    volumes:
      - ./frontend-example/:/app
      - /app/node_modules
    ports:
      - "8080:8080"
  db:
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
    - "5432:5432"

